import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './(pages)/shared/Navbar/page'
import Footer from './(pages)/shared/Footer/page'
import AuthProvider from './provider/AuthProvider'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Car Services',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div className='w-[80%] mx-auto'>
          <Navbar />
          {children}
          
          <Footer/>
          </div>
        </AuthProvider>
      </body>
    </html>
  )
}
